### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by pawamoy** [effigies/mkdocs-branchcustomization-plugin#1]
Hi, could you add a LICENSE file to your repository? It would help to improve https://github.com/pawamoy/best-of-mkdocs contents :slightly_smiling_face: 
If this project is unmaintained, just let me know :+1:

**Comment by effigies** [comment]
Sure. Happy to add. It'll be MIT unless there's a preferred license for the mkdocs ecosystem I should use.

**Comment by effigies** [comment]
Done. Since this has already been in the Python package metadata, I won't tag a new release for now.

**Comment by pawamoy** [comment]
That's great, thank you for the quick response :slightly_smiling_face:
